theme: minima
title: My Practice Site!
author: Tuleine Alshaer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site will show all the different progresses made throughout my html learning experience. You will see me apply my knowledge and practice my skills so i can hopefully master them.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
